dependencies:
  # - <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.5.0 

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'

dotenv: .env
network:
  Excoincial:
    - name: Excoincial Chain Testnet
      chainid: 27082017
      id: Testnet
      host: https://testnet-rpc.exlscan.com/
   
wallets:
  from_key: ${PRIVATE_KEY}


project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests
     